### ISSUE TITLE
Custom logo mobile not show

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [getgrav/grav-theme-quark#193]
Hi.

In Quark theme, when you choose only the **custom_mobile_logo**, this isn't showed, instead is showed the default logo (grav-logo.svg) located in theme://images folder.

However if I choose the **custom_logo**,  there's no problem.

What's wrong?

**Comment by pmoreno-rodriguez** [comment]
Hi.
In my opinion it would be better to use this code, to correct this problem:
```
{% set logo = theme_var('custom_logo_mobile' ?: 'custom_logo') %}
```
I have tried loading only the mobile logo and it works fine.

**Comment by hughbris** [comment]
When I inspect the div `mobile-container` on my site and on the theme demo, its dimensions are 0x0. I assume that is intended on desktop, but there seems to be no media query block that reveals this div for small screen devices.

My guess is that this has just been omitted somehow. I won't make a PR because I don't know the most elegant (S)CSS to fit in with this theme.
