### ISSUE TITLE
Menu only shows "Home" when opening a non-visible page

### ISSUE THREAD

**Issue by Dakicka** [getgrav/grav-theme-quark#55]
I used the one-page skeleton of Quark to create the page and made minimal adjustments.

I have the modular pages and its corresponding links to the sections in the top menu. I also created two non-visible pages for the new GDPR info and the German Impressum. These two pages can only be reached through hyperlinks in the footer. This does work well thus far. If I open one of these two pages, the menu in the header disappears and only the menu point "Home" is visible, which brings me back to the main page.

Is it possible to keep the main menu in the top, like it is on the main page, even if opening different non-visible pages?

**Comment by rhukster** [comment]
The on-page menu is built as it loops over the modular sub-pages.  These sub-pages don't exist in the context of other pages, hence they are not visible.

You can modify the navigation twig and customize it to do whatever you want, even show static links.  Or you could get the collection for the home page's modular sub-pages in the navigation twig and iterate over it.

Really this is a more of a customization question rather than a feature that should be in the default theme which we're keeping intentionally minimal and clean.

**Comment by Dakicka** [comment]
Ah yes, totally makes sense. Thank you!
