### ISSUE TITLE
SVG logo auto inverting

### ISSUE THREAD

**Issue by svatas** [getgrav/grav-theme-quark#72]
When SVG logo of GRAV used it is working properly - when top menu in top of page it is white. When I scroll, the top menu is smaller and the logo is black. That is the way I prefer.

When I change SVG logo with my ovn SVG logo (also Black and White), the logo si not changing (not inverting). Looks like the problem with the SVG file itself. What is the magic behind? What key parameters should be used in SVG logo? When I open the original file, I can not see anything special in it.

I am using GRAV 1.6.0 beta 5 and Quark 2.0 beta 2

**Comment by rhukster** [comment]
The SVG logo is displayed 'inline', the benefit of that as the output is HTML, you can manipulate it with CSS, which is exactly what we're doing here.

The code in SCSS that flips this is in the `_header.scss`:

```
.logo svg path {
    fill: $header-color-dark;
  }

  .header-dark &:not(.scrolled) {
    background: $header-color-dark;
    color: $light-color;
    a {
      color: rgba($light-color, 0.7) !important;
    }
    a.active {
      color: $light-color !important;
    }
    .dropmenu ul ul a {
        color: $dark-color !important;
    }
    .logo svg path {
      fill: $light-color;
    }
  }
```

Basically, this will ONLY work if the SVG has the same structure... So that means the `<path>` values that you want to change the color of using fill.

Read up on this technique here: https://css-tricks.com/cascading-svg-fill-color/

**Comment by aricooperdavis** [comment]
For anyone who finds this:

The .svg logo is only inlined if it is served directly with the theme as the default logo - if you provide a custom logo using the admin interface for the theme then it is wrapped in `<img>` tags and therefore will not be inverted properly.
